### ISSUE TITLE
Integration tests failing

### ISSUE THREAD

**Issue by NohaIhab** [canonical/kserve-operators#105]
integration tests of kserve-controller are failing. logs in https://github.com/canonical/kserve-operators/actions/runs/5024056064/jobs/9009357545 .
Need to investigate and fix.

**Comment by DnPlas** [comment]
The integration tests were failing mainly because of:
1.`istio-operators` not being deployed correctly due to the infra not being configured correctly (incorrect microk8s version and metallb not enabled). It is now fixed.
2. #103 was preventing the tests from finishing. This is also fixed.

You can see that in #107 integration tests are running to completion, so I'm closing this issue. If you have any questions or run into the same thing again, feel free to re-open.
