### ISSUE TITLE
Wrong local gateway namespace in applied `ConfigMap`

### ISSUE THREAD

**Issue by phoevos** [canonical/kserve-operators#150]
The KServe controller charm applies the `inferenceservice-config`, which provides the `ingress` configuration for created Inference Services. As part of this, it sets the local gateway namespace and name: https://github.com/canonical/kserve-operators/blob/5d69093a83449d45af2147b1c722e979b2f4ccb8/charms/kserve-controller/src/templates/configmap_manifests.yaml.j2#L62

Currently, the value of `local_gateway_namespace` is set to `kubeflow` instead of `knative-serving`, despite KNative Serving seemingly [configuring the namespace correctly](https://github.com/canonical/knative-operators/blob/b9632073340126ed43c23b50595bcef5f6b86d66/charms/knative-serving/src/charm.py#L122-L128).

With that in mind, it looks like this is a bug on the KServe side, and more specifically here: https://github.com/canonical/kserve-operators/blob/5d69093a83449d45af2147b1c722e979b2f4ccb8/charms/kserve-controller/src/charm.py#L475

If that is the case, it should be a pretty straightforward fix:
```diff
diff --git a/charms/kserve-controller/src/charm.py b/charms/kserve-controller/src/charm.py
index 74a0daf..719c129 100755
--- a/charms/kserve-controller/src/charm.py
+++ b/charms/kserve-controller/src/charm.py
@@ -373,7 +373,7 @@ class KServeControllerCharm(CharmBase):
                 gateways_context.update(
                     {
                         "local_gateway_name": local_gateway_info["gateway_name"],
-                        "local_gateway_namespace": ingress_gateway_info["gateway_namespace"],
+                        "local_gateway_namespace": local_gateway_info["gateway_namespace"],
                         "local_gateway_service_name": "knative-local-gateway",
                     }
                 )
```

**Comment by DnPlas** [comment]
After some investigation of the issue, we are in fact applying the wrong namespace to the ingress configuration of the local gateway in the [`inferenceservice-config ConfigMap`](https://github.com/canonical/kserve-operators/blob/main/charms/kserve-controller/src/templates/configmap_manifests.yaml.j2#L62), though the fix is slightly different.
The issue happens when rendering [this line](https://github.com/canonical/kserve-operators/blob/main/charms/kserve-controller/src/templates/configmap_manifests.yaml.j2#L62) from

`"localGateway" : "{{ local_gateway_namespace }}/{{ local_gateway_name }}",` to 
`"localGateway" : "kubeflow/knative-local-gateway",` as the [rendering context](https://github.com/canonical/kserve-operators/blob/main/charms/kserve-controller/src/charm.py#L472) establishes. 

The problem with this is that the `localGateway Gateway resource` is not int the `kubeflow` namespace, but in the `knative-serving` namespace. The fix should be:

In the [`inferenceservice-config ConfigMap`](https://github.com/canonical/kserve-operators/blob/main/charms/kserve-controller/src/templates/configmap_manifests.yaml.j2):

```diff
- "localGateway" : "{{ local_gateway_namespace }}/{{ local_gateway_name }}",
- "localGatewayService" : "{{ local_gateway_service_name }}.{{ local_gateway_namespace}}.svc.cluster.local",
+ "localGateway" : "{{ local_gateway_namespace }}/{{ local_gateway_name }}",
+ "localGatewayService" : "{{ local_gateway_service_name }}.{{ ingress_gateway_namespace}}.svc.cluster.local", 
```

In the charm code:

```diff
- "local_gateway_namespace": ingress_gateway_info["gateway_namespace"],
+ "local_gateway_namespace": local_gateway_info["gateway_namespace"],
``
